title: Kyle Wiliams — Portfolio
description: Modular training, cloud security, and compliance labs by Phifyre LLC.
url: https://keambi.github.io/portfolio
baseurl: ""  # Leave empty since you’re publishing from the repo root

theme: jekyll-theme-hacker  # Apply the Hacker theme

author: Kyle Wiliams
github_username: keambi

markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
